// Generated by CoffeeScript 1.10.0
(function() {
  var MainView, myView;

  MainView = (function() {
    function MainView(el) {
      this.el = el;
    }

    MainView.prototype.render = function() {
      var template;
      template = function() {
        return "<div class='blended_grid'>\n\n	<div class='pageHeader'>\n		<h1>Sigil Pal</h1>\n		<h3>automated Statement of intent processor</h3>\n	</div>\n	\n	<div class='pageLeftMenu'>\n		<textarea type='text' id='soi' placeholder='type your intent here'></textarea>\n		<br />\n		<button id='process'>Process Statement of Intent</button>\n	</div>\n	\n	<div class='pageContent'>\n		<div id='result'></div>\n		<br />\n		<p>To find more info on the process of</p>\n		<p>sigilization and magick in general</p>\n		<p>go <a href='http://www.excommunicate.com/basics-in-sigil-creation-or-the-only-magic-guaranteed-to-work/#axzz4Ej3q2KlR'>here</a> or <a href='http://www.chaosmatrix.org/library/chaos_all.php'>here</a> for more detailed information.</p>\n	</div> \n	<div class='pageFooter'>\n		<h4><a href='https://github.com/theblacksquid'>@theblacksquid</a> 2016</h4>\n	</div>\n</div>";
      };
      $(this.el).append(template());
      return this.resultView();
    };

    MainView.prototype.resultView = function() {
      var template;
      template = function(input) {
        return "<div>\n	<h3>" + ($('#soi').val()) + "</h3>\n	<p>Base Letters: " + input.BaseChars + "</p>\n	<p>Numeric Value: " + input.NumVal + "</p>\n	<p>Seed Number: " + input.SeedNum + "</p>\n</div>";
      };
      return $("#process").click(function() {
        var text;
        text = $("#soi").val();
        return $("#result").html(template(digest(text)));
      });
    };

    return MainView;

  })();

  myView = new MainView("#app");

  myView.render();

}).call(this);
