// Generated by CoffeeScript 1.10.0

  var digest, getBaseChars, getNumVal, getSeedNum, numerology;

  numerology = {
    'A': 1,
    'B': 2,
    'C': 3,
    'D': 4,
    'E': 5,
    'F': 6,
    'G': 7,
    'H': 8,
    'I': 9,
    'J': 10,
    'K': 11,
    'L': 12,
    'M': 13,
    'N': 14,
    'O': 15,
    'P': 16,
    'Q': 17,
    'R': 18,
    'S': 19,
    'T': 20,
    'U': 21,
    'V': 22,
    'W': 23,
    'X': 24,
    'Y': 25,
    'Z': 26
  };

  getNumVal = function(str) {
    var arr, numbers;
    arr = str.replace(/[^a-zA-Z ]/g, "").toUpperCase().split("").filter(function(value) {
      return !(value === " ");
    });
    numbers = [];
    arr.forEach((function(val) {
      return numbers.push(numerology[val]);
    }));
    return numbers.reduce((function(x, y) {
      return x + y;
    }));
  };

  getSeedNum = function(num) {
    var arr, result;
    arr = num.toString().split("").map((function(x) {
      return +x;
    }));
    while (arr.length > 1) {
      result = arr;
      result = result.reduce((function(x, y) {
        return x + y;
      }));
      arr = result.toString().split("").map(function(x) {
        return +x;
      });
    }
    while (arr[0] < 3) {
      arr[0] = arr[0] + 1;
    }
    return arr[0];
  };

  getBaseChars = function(str) {
    var arr, result;
    arr = str.replace(/[^a-zA-Z ]/g, "").toUpperCase().split("").filter((function(x) {
      return !(x === " ");
    }));
    result = [];
    arr.forEach((function(x) {
      if (!(result.includes(x))) {
        return result.push(x);
      }
    }));
    return result;
  };

  digest = function(str) {
    var result;
    return result = {
      BaseChars: getBaseChars(str),
      NumVal: getNumVal(str),
      SeedNum: getSeedNum(getNumVal(str))
    };
  };


